
{% set cf_buildnumber = "1" %}
{% set py_tag = "py" + PY_VER|replace('.','') %}
{% set intel_ch = "https://software.repos.intel.com/python/conda" %}

# gonna have to change these every time we repack new SVS packages
# scalable-vs repack info
{% set intel_buildnumber = "0" %}
{% set build_string = "g62f5782" %}
{% set version = "0.2.0" %}
{% set sha256_map = {
  "py310": "1f7f0c71e6cfc755688a8990ec48ed82504b2a3e6a4f0a946d285438a19d0be2",
  "py311": "acf036277bd8830e288aa892eae433318c3b65d3dab5a08798d5b6dfa2363509",
  "py312": "15e0b407e54a26147ca072e52f6369d09e8c312ae01c5daa4dae7ae44874e53b",
  "py313": "e8944825469ef6de24dce58f600b96cdb9ef7ea49da91030cfbf4529afd51348"
} %}
# libsvs repack info
{% set libsvs_build_string = "gd549b83" %}
{% set libsvs_sha256 = "8ec83ca9e311ad642b2fd6fe20fb27c0021fb679d508bc5f7b3a1a55c4cb8581" %}
# libsvs-runtime repack info
{% set libsvs_runtime_build_string = "gd549b83" %}
{% set libsvs_runtime_sha256 = "4e11657eff0ec055ee12845026a61313ad919ff1181514ef2f44453e87658e86" %}

# builds off above variables
{% set url_string =  build_string + py_tag + "_" + intel_buildnumber %}
{% set full_build_string = url_string + "_" + cf_buildnumber %}
{% set libsvs_url_string =  libsvs_build_string + "_" + intel_buildnumber %}
{% set libsvs_full_build_string = libsvs_url_string + "_" + cf_buildnumber %}
{% set libsvs_runtime_url_string =  libsvs_runtime_build_string + "_" + intel_buildnumber %}
{% set libsvs_runtime_full_build_string = libsvs_runtime_url_string + "_" + cf_buildnumber %}

package:
  name: scalable-vs-packs
  version: {{ version }}

source:
  - url: {{ intel_ch }}/{{ target_platform }}/scalable-vs-{{ version }}-{{ url_string }}.conda
    folder: scalable-vs
    sha256: {{ sha256_map.get(py_tag, "") }}
    no_hoist: true
  - url: {{ intel_ch }}/{{ target_platform }}/libsvs-{{ version }}-{{ libsvs_url_string }}.conda
    folder: libsvs
    sha256: {{ libsvs_sha256 }}
    no_hoist: true
  - url: {{ intel_ch }}/{{ target_platform }}/libsvs-runtime-{{ version }}-{{ libsvs_runtime_url_string }}.conda
    folder: libsvs-runtime
    sha256: {{ libsvs_runtime_sha256 }}
    no_hoist: true

build:
  number: {{ cf_buildnumber }}
  binary_relocation: false
  detect_binary_files_with_prefix: false
  skip: True  # [not (linux64) or py>313]
  missing_dso_whitelist:
    - /lib64/ld-linux-x86-64.so.2
    - /lib64/libpthread.so.0
    - /lib64/libm.so.6
    - /lib64/libdl.so.2
    - /lib64/libc.so.6

outputs:
  - name: scalable-vs
    version: {{ version }}
    script: repack.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ full_build_string }}
      binary_relocation: false
      detect_binary_files_with_prefix: false
      missing_dso_whitelist:
        - /lib64/ld-linux-x86-64.so.2
        - /lib64/libpthread.so.0
        - /lib64/libm.so.6
        - /lib64/libdl.so.2
        - /lib64/libc.so.6
      ignore_run_exports:
        - python
        - libgomp
    requirements:
      host:
        - python
        - conda-package-handling
      run:
        - python
        - numpy
        - toml
        - libstdcxx
        - libgcc
        - libgfortran5
        - libgomp

    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - scalable-vs/info/licenses/distributions/LICENSE
        - scalable-vs/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search
      description: |
        <strong>LEGAL NOTICE: Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://www.intel.com/content/www/us/en/content-details/749362/intel-simplified-software-license-version-october-2022.html" target="_blank">Intel Simplified Software License (Version October 2022)</a>
        <br/><br/>
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    
    test:
      requires:
        - python
        - numpy
        - toml
      commands:
        - python -c "import sys,os; print('Python:',sys.version); import svs; print('svs ok', svs.library_version())"

  - name: libsvs
    version: {{ version }}
    script: repack_libsvs.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ libsvs_full_build_string }}
      skip: True  # [not linux64]
      binary_relocation: false
      detect_binary_files_with_prefix: false
      missing_dso_whitelist:
        - /lib64/ld-linux-x86-64.so.2
        - /lib64/libpthread.so.0
        - /lib64/libm.so.6
        - /lib64/libdl.so.2
        - /lib64/libc.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libm.so.6
        - $RPATH/libdl.so.2
        - $RPATH/libc.so.6
    requirements:
      host:
        - conda-package-handling
      run:
        - libstdcxx
        - libgcc
    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - libsvs/info/licenses/distributions/LICENSE
        - libsvs/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search library
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    test:
      commands:
        - test -f $PREFIX/lib/libsvs_shared_library.so
        - test -f $PREFIX/lib/libsvs_static_library.a
        - test -f $PREFIX/include/svs/leanvec/leanvec.h

  - name: libsvs-runtime
    version: {{ version }}
    script: repack_libsvs_runtime.sh
    number: {{ cf_buildnumber }}
    build:
      string: {{ libsvs_runtime_full_build_string }}
      skip: True  # [not linux64]
      binary_relocation: false
      detect_binary_files_with_prefix: false
      missing_dso_whitelist:
        - /lib64/ld-linux-x86-64.so.2
        - /lib64/libpthread.so.0
        - /lib64/libm.so.6
        - /lib64/libdl.so.2
        - /lib64/libc.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libm.so.6
        - $RPATH/libdl.so.2
        - $RPATH/libc.so.6
      ignore_run_exports:
        - libgomp
        - _openmp_mutex
    requirements:
      host:
        - conda-package-handling
      run:
        - libstdcxx
        - libgcc
        - libgomp
        - _openmp_mutex
    about:
      home: https://intel.github.io/ScalableVectorSearch/index.html
      license: Intel Simplified Software License (Version October 2022)
      license_file:
        - libsvs-runtime/info/licenses/distributions/LICENSE
        - libsvs-runtime/info/licenses/ScalableVectorSearch/THIRD-PARTY-PROGRAMS
      summary: Scalable Vector Search runtime library
      dev_url: https://github.com/intel/ScalableVectorSearch
      doc_url: https://intel.github.io/ScalableVectorSearch/index.html
    test:
      commands:
        - test -f $PREFIX/lib/libsvs_runtime.so
        - test -f $PREFIX/include/svs/runtime/api_defs.h

# pleases the linter
about:
  home: https://github.com/conda-forge/scalable-vs-feedstock
  license: LicenseRef-IntelSimplifiedSoftwareOct2022
  summary: 'Repackaged Intel Scalable Vector Search'

extra:
  feedstock-name: scalable-vs-packs
  recipe-maintainers:
    - jharlow-intel
    - napetrov
    - mihaic
    - ethanglaser
